version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client-dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enable hot reload on Windows/Docker
    command: npm run dev -- --host 0.0.0.0  # Allow external connections

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend-dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=your-secret-key-here
    command: python manage.py runserver 0.0.0.0:8000
